const config = {
  baseUrl: 'https://www.finansportalen.no/insurance-calculator/rest/classifier/car/registrationYear',
  classifyUrl: 'https://www.finansportalen.no/insurance-calculator/rest/classifier/car/carModel',
  carVariantUrl: 'https://www.finansportalen.no/insurance-calculator/rest/classifier/car/carVariant',
  carCodes: [
    { "code": "1100", "message": "Alfa Romeo" },
    { "code": "1170", "message": "Aston Martin" },
    { "code": "1230", "message": "Audi" },
    { "code": "1350", "message": "Bentley" },
    { "code": "1400", "message": "BMW" },
    { "code": "1500", "message": "Buick" },
    { "code": "1550", "message": "Cadillac" },
    { "code": "2650", "message": "Chevrolet" },
    { "code": "1650", "message": "Chevrolet US" },
    { "code": "1700", "message": "Chrysler" },
    { "code": "1750", "message": "Citroën" },
    { "code": "3290", "message": "Dacia" },
    { "code": "3330", "message": "Daewoo" },
    { "code": "2030", "message": "Daihatsu" },
    { "code": "2250", "message": "Dodge" },
    { "code": "256", "message": "DS" },
    { "code": "2400", "message": "Ferrari" },
    { "code": "2450", "message": "Fiat" },
    { "code": "1199", "message": "Fisker" },
    { "code": "2600", "message": "Ford" },
    { "code": "3580", "message": "Galloper" },
    { "code": "7740", "message": "Honda" },
    { "code": "4030", "message": "Hummer" },
    { "code": "3390", "message": "Hyundai" },
    { "code": "4330", "message": "Infiniti" },
    { "code": "2003", "message": "Infiniti" },
    { "code": "3240", "message": "Isuzu" },
    { "code": "3310", "message": "Iveco" },
    { "code": "3400", "message": "Jaguar" },
    { "code": "3510", "message": "Jeep" },
    { "code": "3420", "message": "Kewet" },
    { "code": "7630", "message": "Kewet Buddy" },
    { "code": "3450", "message": "Kia" },
    { "code": "5610", "message": "Lada/VAZ" },
    { "code": "3700", "message": "Lancia" },
    { "code": "4953", "message": "Land Rover" },
    { "code": "9970", "message": "Lexus" },
    { "code": "3920", "message": "Maserati" },
    { "code": "3930", "message": "Mazda" },
    { "code": "3900", "message": "Mercedes-Benz" },
    { "code": "4000", "message": "MG" },
    { "code": "3690", "message": "MINI" },
    { "code": "4011", "message": "Mitsubishi" },
    { "code": "4050", "message": "Morgan" },
    { "code": "2001", "message": "Nissan" },
    { "code": "4350", "message": "Opel" },
    { "code": "4500", "message": "Peugeot" },
    { "code": "8520", "message": "Piaggio" },
    { "code": "4550", "message": "Plymouth" },
    { "code": "4650", "message": "Pontiac" },
    { "code": "4700", "message": "Porsche" },
    { "code": "4800", "message": "Renault" },
    { "code": "4900", "message": "Rolls-Royce" },
    { "code": "4951", "message": "Rover" },
    { "code": "5090", "message": "Seat" },
    { "code": "5150", "message": "Skoda" },
    { "code": "3590", "message": "Smart" },
    { "code": "3440", "message": "SsangYong" },
    { "code": "3440", "message": "Ssangyong" },
    { "code": "5260", "message": "Subaru" },
    { "code": "8380", "message": "Suzuki" },
    { "code": "5000", "message": "Saab" },
    { "code": "4360", "message": "Tesla" },
    { "code": "3560", "message": "Think" },
    { "code": "5480", "message": "Toyota" },
    { "code": "5750", "message": "Volkswagen" },
    { "code": "5800", "message": "Volvo" }
  ]
};

module.exports = config;